name: aurallion
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37763
title: aurallion pictures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfded9'
    - '#b0c0b6'
    - '#23282e'
    - '#5a5d54'
    - '#788073'
  brandStrength: 0.5
  lightness: 0.4263944097328931
  saturation: 0.6489098435267806
  rhythmicContrast: 0.3820370768662542
purpose: []
